### ISSUE TITLE
brew add fails if 'mas' dependencies are present in Brewfile

### ISSUE THREAD

**Issue by boldandbrad** [superatomic/homebrew-bundle-extensions#1]
consider a Brewfile that contains the line:

```ruby
mas 'Twitter', id: 1482454543
```

when running `brew add wget`, I get the following error:

```txt
Error: undefined method `<<' for nil:NilClass
/usr/local/Homebrew/Library/Taps/superatomic/homebrew-bundle-extensions/cmd/add.rb:62:in `block in add'
/usr/local/Homebrew/Library/Taps/superatomic/homebrew-bundle-extensions/cmd/add.rb:57:in `each'
/usr/local/Homebrew/Library/Taps/superatomic/homebrew-bundle-extensions/cmd/add.rb:57:in `add'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

If I remove or comment out my `mas` dependencies, `brew add` completes just fine.

I don't think `brew add` needs to support adding new `mas` dependencies - as that would be more complex, but it should be able to handle them being present.

**Comment by superatomic** [comment]
Thank you for reporting this issue! I don't use `mas` myself so I assumed that `brew add` would just ignore any `mas` lines.
It's very likely that this also affects anyone using `whalebrew` in their Brewfile.

**Comment by superatomic** [comment]
Thanks again for reporting this and providing so much helpful information! My fix in #2 should have resolved this issue, so you should only have to run `brew update` to fix the problem.

Also, I'd like to thank you for offering to submit a PR to fix this bug yourself. I was happy to do it for you, but I want to applaud your willingness to spend your own time to submit a fix.

**Comment by superatomic** [comment]
Also, I'm open to expanding `brew add` to be able to add `mas` applications to a Brewfile as well. As far as I can tell, there's no precedent for specifying `mas` applications in the official brew commands, but either `brew add --mas [NAME|ID]` or `brew mas [NAME|ID]` seem like they would fit in this repo.

If this is something that you think would be useful I can work on adding it at some point. (or if you want to, you could implement it yourself and submit a PR; just open a new issue to discuss)

**Comment by boldandbrad** [comment]
Just did `brew update` and it now works! Thank you for the quick turn around and the kind words! I really like this tool as neither Homebrew core or bundle offer an official solution for this right now and I didn't want to write one myself 😅

**Comment by boldandbrad** [comment]
As far as `mas` support goes, I think it would be a neat addition. I personally think `brew add --mas` would be most consistent.

`mas` Brewfile lines I've seen are typically formatted like: `mas "name", id: 12345678`

As far as I know (I could be wrong), the value of the name doesn't actually matter. I think its just there to make the entry human readable - `mas` only requires an ID for install.

The command would probably have to take 2 params, string NAME, and string/int ID - unless `add` utilized `mas` under the hood to pull NAME by id (probably overkill/incompatible/not sure if possible).

I'd be happy to discuss further though if you'd like input! Thanks again!

**Comment by boldandbrad** [comment]
Ideally for me, I'd like to write little shell functions that live in my dotfiles that `brew install __ && brew add __` formulae/casks.

On the flip side, it may be nice to have a `remove` command as well to remove a line from the Brewfile. This would make possible functions that `brew uninstall __ && brew remove __`

Let me know if you're open to this and I'd be happy to help! No worries though if not!

**Comment by superatomic** [comment]
Currently, `brew add` detects formula and casks the same way that built-in commands do, like this:
https://github.com/superatomic/homebrew-bundle-extensions/blob/719baf9c0fa3485db9ed1482aa7fab1327f3d9ca/cmd/add.rb#L27
https://github.com/superatomic/homebrew-bundle-extensions/blob/719baf9c0fa3485db9ed1482aa7fab1327f3d9ca/cmd/add.rb#L35

I don't know how easy it is to overload this for supporting `mas`, which is why I suggested a separate `brew mas` command, but I do see the appeal of having `brew add` work for everything. I'll play around with it and see what I can do. If I can get it to work by modifying `brew add`, I'd do that.

Ruby makes it really easy to call shell commands from code, so it's very possible to directly interact with the `mas` command. The behavior that I would love for `brew add --mas`/`brew mas` would to the ability to specify either a name, an ID, or both. So in the case of `brew add --mas Twitter` it would search the App Store, ask whether it found the correct app, and add it to the Brewfile if so. Ideally, I think this is good:

- `brew add --mas Twitter`
- `brew add --mas 1482454543`
- `brew add --mas NotTwitter:1482454543`

But I'll have to see the information that `mas` actually provides.

**Comment by boldandbrad** [comment]
I'm following what you're saying. The only benefits to having `brew add` handle all scopes are: consistency, and the fact that you wouldn't need to handle `brew mas --add vs brew mas --remove` if that functionality eventually exists.

In order to get the data you'd need from `mas` you'd need to rely on `mas search "NAME"`, which returns a list of potential apps and their ids. You'd then have to select the exact match by name if it exists or default to the first in the list or prompt for user input to select.

I'll do some research too though and see what I come up with!

Also as far as naming goes, I personally like `brew drop` in place of `remove`. But `delete` could work also.

**Comment by boldandbrad** [comment]
Should I create issues for both of these ideas so we can further discuss and track changes there?

**Comment by superatomic** [comment]
That sounds good. I created an issue for the `brew drop` command (I really like your idea for the name): #3.
I'd appreciate it if you opened an issue for supporting `mas`.
